### PR TITLE
feat: added custom type for LogLevel

### PR DESCRIPTION
**Pull request by escarls**
With this type you will get a slog.LogLevel from the variable and if the value is not recognized, it will just return slog.LevelInfo

### CODE REVIEW

**Comment by audunmo** [comment]
Is this going to be merged?

**Comment by engvik** [comment]
We should probably add the `go` directive to `go.mod` to indicate that this must be built with go1.21 and above.

**Comment by engvik** [comment]
Sorry for the back and forth, I know that I was the one pointing you in this direction, but after thinking about it. It makes sense to add support for this in our internal logger package. Are you OK with that?

**Comment by escarls** [comment]
Closing this, as I've moved the code to [cloud/logger](https://github.com/reMarkable/cloud/pull/575)

**Pull request closed without merging**
